name: Build and Push Container

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: prj-saudefamiliar-pessoal-pfl
  GAR_LOCATION: southamerica-east1
  GAR_REPOSITORY: saude-familiar
  IMAGE_NAME: saude-familiar

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: projects/751378940559/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
          service_account: sa-saudefamiliar-deploy@prj-saudefamiliar-pessoal-pfl.iam.gserviceaccount.com

      - name: Authenticate Docker to Artifact Registry
        uses: docker/login-action@v4
        with:
          registry: southamerica-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build container
        run: |
          docker build \
            -t "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}" \
            -t "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:v0.1" \
            .

      - name: Push container
        run: |
          docker push "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}"
          docker push "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:v0.1"

      - name: Show published image
        run: |
          echo "Published:"
          echo "${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:v0.1"
